import type { Sale } from '@/lib/types';
import { subDays } from 'date-fns';

export const sales: Sale[] = [
  {
    id: 'SALE-001',
    clientName: 'Fábio Hoffmann',
    project: 'Morada Serena',
    builder: 'Tenda',
    saleValue: 250000,
    downPayment: 750,
    status: 'Venda Concluída / Paga',
    saleDate: subDays(new Date(), 15).toISOString(),
    lastStatusUpdate: subDays(new Date(), 15).toISOString(),
    agentName: 'Carlos Pereira',
    notes: 'Cliente satisfeito, comissão paga.',
  },
  {
    id: 'SALE-002',
    clientName: 'Luana Vanessa',
    project: 'Solar dos Pássaros',
    builder: 'Vasco',
    saleValue: 320000,
    downPayment: 0,
    status: 'Assinatura Pendente',
    saleDate: subDays(new Date(), 5).toISOString(),
    lastStatusUpdate: subDays(new Date(), 2).toISOString(),
    agentName: 'Sofia Andrade',
    notes: 'Aguardando assinatura do contrato pelo cliente. Previsto para amanhã.',
  },
  {
    id: 'SALE-003',
    clientName: 'Cleber e Ana',
    project: 'Parque do Mirante',
    builder: 'MRV',
    saleValue: 190000,
    downPayment: 500,
    status: 'Em Análise de Crédito',
    saleDate: subDays(new Date(), 25).toISOString(),
    lastStatusUpdate: subDays(new Date(), 20).toISOString(),
    agentName: 'Carlos Pereira',
    notes: 'Cliente está regularizando pendências no SPC.',
  },
  {
    id: 'SALE-004',
    clientName: 'Luísa dos Santos',
    project: 'Solar do Bosque',
    builder: 'Outra',
    saleValue: 210000,
    downPayment: 1000,
    status: 'Venda Caída / Cancelada',
    saleDate: subDays(new Date(), 40).toISOString(),
    lastStatusUpdate: subDays(new Date(), 30).toISOString(),
    agentName: 'Fernanda Lima',
    notes: 'Caiu na análise de crédito do banco.',
  },
  {
    id: 'SALE-005',
    clientName: 'Marcos Vinicius',
    project: 'Residencial Flores',
    builder: 'Tenda',
    saleValue: 280000,
    downPayment: 1500,
    status: 'Novo Cadastro',
    saleDate: new Date().toISOString(),
    lastStatusUpdate: new Date().toISOString(),
    agentName: 'Sofia Andrade',
  },
  {
    id: 'SALE-006',
    clientName: 'Juliana Paes',
    project: 'Villa das Águas',
    builder: 'Vasco',
    saleValue: 450000,
    downPayment: 2000,
    status: 'Aprovado / Aguardando Unidade',
    saleDate: subDays(new Date(), 10).toISOString(),
    lastStatusUpdate: subDays(new Date(), 4).toISOString(),
    agentName: 'Carlos Pereira',
    notes: 'Crédito aprovado, aguardando liberação da unidade pela construtora.',
  },
  {
    id: 'SALE-007',
    clientName: 'Ricardo Alves',
    project: 'Morada Serena',
    builder: 'Tenda',
    saleValue: 255000,
    downPayment: 800,
    status: 'Em Análise de Crédito',
    saleDate: subDays(new Date(), 45).toISOString(),
    lastStatusUpdate: subDays(new Date(), 42).toISOString(),
    agentName: 'Fernanda Lima',
    notes: 'Documentação enviada para o banco.',
  },
  {
    id: 'SALE-008',
    clientName: 'Beatriz Costa',
    project: 'Solar dos Pássaros',
    builder: 'Vasco',
    saleValue: 330000,
    downPayment: 2500,
    status: 'Venda Concluída / Paga',
    saleDate: subDays(new Date(), 50).toISOString(),
    lastStatusUpdate: subDays(new Date(), 48).toISOString(),
    agentName: 'Sofia Andrade',
  },
];
